### ISSUE TITLE
Assemble the Final Governor Contract

### ISSUE THREAD

**Issue by apbendi** [gitcoinco/Alpha-Governor-Upgrade#2]
Compose the final Governor contract from the appropriate OpenZeppelin extensions to ensure:

* Configurable governance parameters
* Bravo compatibility
* Compatibility with the existing GTC token and Timelock contracts

**Comment by mds1** [comment]
I was going to ask this in #1 but I think here is more appropriate: Do we have a final spec of what governor features are desired? For example `GovernorPreventLateQuorum` is interesting, there may be other extensions worth considering too

**Comment by apbendi** [comment]
Hey @mds1, good question. The spec is basically "Bravo compatible Governor with configurable governance params with least disruption possible for the migration." There will definitely be some things we need to nail down as we work through it but that's the goal. Let me know if you have any more specific questions.
